version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "82:80"
    networks:
      - redDocker
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - redDocker

networks:
  redDocker:
    
