version: '3'
services:
  drupal:
    image: drupal
    ports:
      - "81:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: 'drupal'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  drupal_data:
  mysql_data:
  
